# Generated by Django 2.2.17 on 2021-04-03 12:55

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20210328_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=authapp.models.default_expire_time),
        ),
    ]
